alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias l='ls -CF --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -alF --color=auto'
alias ls='ls --color=auto'
alias pass-gen='</dev/urandom tr -dc '1234567890!@#%+qQwWeErRtTyYuUpPaAsSdDfFgGhHjJkKzZxXcCvVbBnNmM_-' | head -c18; echo '
