iraw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x282a35"
blue = "0x61d0ff"
cyan = "0x09efd0"
green = "0x85e084"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xe6f074"

[colors.normal]
black = "0x000000"
blue = "0x7abcf5"
cyan = "0x09efd0"
green = "0x75b774"
magenta = "0xff79c6"
red = "0xfb6767"
white = "0xbfbfbf"
yellow = "0xe6f074"

[colors.primary]
background = "0x2b2a22"
foreground = "0xf0c674"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[window]
title = "Terminal"
