require('mechanicus.autocmd')
require('mechanicus.options')
require('mechanicus.commands')
require('mechanicus.colorscheme').setup()
require('mechanicus.keybindings')
require('mechanicus.lazy')
require('mechanicus.setups')
